# scene
scene: gibson
scene_id: Rs
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: no_obj
trav_map_resolution: 0.1
trav_map_erosion: 2
should_open_all_doors: true

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

robot:
  name: Tiago
  action_type: continuous
  action_normalize: true
  proprio_obs:
    - eef_left_pos
    - eef_left_quat
    - eef_right_pos
    - eef_right_quat
    - trunk_qpos
    - arm_left_qpos_sin
    - arm_left_qpos_cos
    - gripper_left_qpos
    - arm_right_qpos_sin
    - arm_right_qpos_cos
    - gripper_right_qpos
    - grasp_left
    - grasp_right
  reset_joint_pos: null
  base_name: null
  scale: 1.0
  self_collision: true
  rendering_params: null
  grasping_mode: physical
  rigid_trunk: true
  default_trunk_offset: 0.14
  default_arm_pose: vertical
  controller_config:
    base:
      name: JointController
    arm_left:
      name: JointController
      motor_type: position
      use_constant_goal_position: true
      constant_goal_position: [-1.10, 1.47, 2.71, 1.71, -1.57, 1.39, 0.0]
    gripper_left:
      name: JointController
      motor_type: position
      use_constant_goal_position: true
      constant_goal_position: [0.04, 0.04]
    arm_right:
      name: JointController
      motor_type: position
      use_constant_goal_position: true
      constant_goal_position: [-1.10, 1.47, 2.71, 1.71, -1.57, 1.39, 0.0]
    gripper_right:
      name: JointController
      motor_type: position
      use_constant_goal_position: true
      constant_goal_position: [0.04, 0.04]
    camera:
      name: JointController
      motor_type: position
      use_constant_goal_position: true
      constant_goal_position: [0.0, 0.0]


# task
task: point_nav_random
target_dist_min: 1.0
target_dist_max: 10.0
goal_format: polar
task_obs_dim: 4

# reward
reward_type: geodesic
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.1

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36  # body width
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# sensor spec
output: [task_obs, rgb, depth, occupancy_grid, scan, scan_rear]
# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
fisheye: false
image_width: 640
image_height: 480
vertical_fov: 45
# depth
depth_low: 0.8
depth_high: 3.5
# scan
# Hokuyo URG-04LX-UG01
# https://www.hokuyo-aut.jp/search/single.php?serial=166
# n_horizontal_rays is originally 683, sub-sampled 1/3
# n_horizontal_rays: 228
# n_vertical_beams: 1
laser_linear_range: 10.0
laser_angular_range: 180.0
min_laser_dist: 0.0
laser_link_name: base_front_laser_link
laser_link_rear_name: base_rear_laser_link

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visible_target: true
visible_path: false
