# Example Tiago config
robot:
  name: Tiago
  action_type: continuous
  action_normalize: true
  proprio_obs:
    - eef_left_pos
    - eef_left_quat
    - eef_right_pos
    - eef_right_quat
    - trunk_qpos
    - arm_left_qpos_sin
    - arm_left_qpos_cos
    - gripper_left_qpos
    - arm_right_qpos_sin
    - arm_right_qpos_cos
    - gripper_right_qpos
    - grasp_left
    - grasp_right
  reset_joint_pos: null
  base_name: null
  scale: 1.0
  self_collision: true
  rendering_params: null
  grasping_mode: physical
  rigid_trunk: false
  default_trunk_offset: 0.365
  default_arm_pose: vertical
  controller_config:
    base:
      name: JointController
    arm_left:
      name: InverseKinematicsController
    gripper_left:
      name: MultiFingerGripperController
    arm_right:
      name: InverseKinematicsController
    gripper_right:
      name: MultiFingerGripperController
    camera:
      name: JointController